export const ROUTES = {
  home: "/",
  adminLogin: "/adminpage",
  adminChargeRequests: "/adminpage/charge-requests",
  adminSelect: "/admin-select",
  adminUserManagement: "/adminpage/user-management",
  adminTeamManagement: "/adminpage/team-management",
  charge: "/charge",
  checkResult: "/check-result",
  codeReader: "/code-reader",
  describe: "/describe",
  guide: "/guide",
  heart: "/heart",
  hobby: "/hobby",
  loading: "/loading",
  matching: "/matching",
  matchResult: "/match-result",
  profileBuilder: "/profile-builder",
  qrGenerator: "/QR-generator",
  redirection: "/redirection",
  userInfo: "/userinfo",
} as const;
